## Linear regression

In [6]:
import numpy as np

%matplotlib inline
from mpl_toolkits import mplot3d
import numpy as np
import matplotlib.pyplot as plt

In [7]:
def linear_regression():
    # Step # 1 - Extract data
    pointsStart = np.genfromtxt('ml.csv', delimiter=',')
    points = np.genfromtxt('ml.csv', delimiter=',')
        
    # Step # 2 - Define hyperparameters
    
    ## Learning rate
    learning_rate_const = 0.01
    
    ## Coefficients y = a * x + b
    init_1 = 0
    init_2 = 0
    
    init_3 = 0
    
    
    
    
    
    ## number of iterations
    num_iterations = 10000
    
    ## our expected error 
    expected_error = 0.0001
    
     ## normilize our data
    #points = normalize4(points)
    
    # Step 3 - model training
    
    print(
        'Start learning at a = {0}, b = {1}, c = {2}, error = {4}'.format(
            init_1,
            init_2,
            init_3,
            compute_error(init_1, init_2, init_3, points)
        )
    )
    
    
    
   
    
    a, b, c = gradient_descent(init_1, init_2, init_3,  points, learning_rate_const, num_iterations, expected_error)
    
    print(
        'End learning at a = {0}, b = {1}, c = {2}, error = {4}'.format(
            a,
            b,
            c,
            compute_error(a, b, c,  points)
        )
    )
    
    return a, b, c


def compute_error(a, b, c, points):
    error = 0
    N = len(points)
    for i in range(N):
        x1 = points[i, 1]
        x2 = points[i, 2]
        y = points[i, 0]

        
        error += (y- (a * x1 + b * x2 + c))**2
    e = np.eye(points.shape[1])
    error + (a,b,c)*e
    return error/N 
   
    
def normalize(array):
    for j in range(array.shape[1]):
        array[:, j] = (array[:, j] - np.min(array[:, j])) /(np.max(array[:, j]) - np.min(array[:, j]))
    return array
    
def normalize2(array):
    for j in range(array.shape[1]):
        array[:, j] = array[:, j]/np.max(array[:, j])
    return array
           
def normalize3(array):
    for j in range(array.shape[1]):
        array[:, j] = array[:, j]/np.max(array[:, j])
    for j in range(array.shape[1]):
        array[:, j] = array[:, j]/np.max(array[:, j])
    return array
           
           
def normalize4(array):
    for j in range(array.shape[1]-1):
        array[:, j] = (array[:, j] - array[:, j].mean()) / array[:, j].std()
    return array

def gradient_descent(starting_a, starting_b,starting_c, points, learning_rate_const, num_iterations, expected_error):
    '''
        Performs gradient step num_iterations times
        in order to find optimal a, b values
    '''
    a = starting_a
    b = starting_b
    c = starting_c
    
    for i in range(num_iterations):
        learning_rate = learning_rate_const/float(i+1)
        a,b,c = gradient_step(a, b, c, points, learning_rate)
        if (expected_error >  compute_error(a, b, c, points)):
            break
    
    return a, b, c
    

def gradient_step(current_a, current_b, current_c,  points, learning_rate):
    '''
        Updates a and b in antigradient direction
        with given learning_rate
    '''
    a = current_a
    b = current_b
    c = current_c
    
    grad_a = 0
    grad_b = 0
    grad_c = 0
    
    
    N = len(points)
    
    for i in range(N):
        y = points[i, 0]
        x1 = points[i, 1]
        x2 = points[i, 2]
        
        grad_a += - (2/N) * (y - (a*x1 + b*x2 + c))*x1
        grad_b += - (2/N) * (y - (a*x1 + b*x2 + c))*x2
        grad_c += - (2/N) * (y - (a*x1 + b*x2 + c))
    
    a = current_a - learning_rate * grad_a
    b = current_b - learning_rate * grad_b
    c = current_c - learning_rate * grad_c
    
    return a,b,c

In [9]:
a, b, c = linear_regression()

In [2]:
print("hello")
points = np.genfromtxt('ml.csv', delimiter=',')
print(points)

hello
[[  nan   nan   nan]
 [ 132.   52.  173.]
 [ 143.   59.  184.]
 [ 153.   67.  194.]
 [ 162.   73.  211.]
 [ 154.   64.  196.]
 [ 168.   74.  220.]
 [ 137.   54.  188.]
 [ 149.   61.  188.]
 [ 159.   65.  207.]
 [ 128.   46.  167.]
 [ 166.   72.  217.]]


In [ ]:
for j in range(points.shape[1]):
    points[:, j] = (points[:, j] - np.min(points[:, j])) /(np.max(points[:, j]) - np.min(points[:, j]))
print(points)

## Plot Cost funstion

In [ ]:
def plot_decorator(f):
    points = np.genfromtxt('ml.csv', delimiter=',')
    
    return lambda a, b: f(a, b, points)


cost = plot_decorator(compute_error)

In [ ]:
points = np.genfromtxt('ml.csv', delimiter=',')
A = np.linspace(-10, 12, 40)
B = np.linspace(-10, 12, 40)

A, B = np.meshgrid(A, B)
E = cost(A, B)
print(E)

In [ ]:
fig = plt.figure()
ax = plt.axes(projection='3d')
ax.contour3D(A, B, E, 1000)
ax.set_xlabel('a')
ax.set_ylabel('b')
ax.set_zlabel('cost')

## Plot data and learned function

In [ ]:
points = np.genfromtxt('ml.csv', delimiter=',')
X = points[:, 0]
Y = points[:, 1]

plt.xlim(0, 80)
plt.ylim(0, 150)
plt.scatter(X, Y)

params = np.linspace(0, 150, 10)

plt.plot(params, a * params + b)

plt.show()
